{{ if or (.Values.allowNFS.enabled) (.Values.allowLocal.enabled) (.Values.allowEFS.enabled)}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
{{ if  .Values.allowLocal.enabled }}
  storageClassName: "local-storage"
  volumeName: shared-pv-{{ .Release.Namespace }}
{{ else if .Values.allowNFS.enabled }}
  storageClassName: ""
  volumeName: shared-pv-{{ .Release.Namespace }}
{{ else if .Values.allowEFS.enabled }}
  storageClassName: "efs-sc"
{{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.graderSetupService.storageRequests | default "200Mi" | quote }}
{{ end }}