{{ if .Values.allowEFS.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-shared-volume
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: {{ .Release.Name }}-shared-volume
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 11Gi

{{ end }}