{{ if .Values.allow_external_dns.enabled }}

{{ if .Values.allowExternalDNS.enableIRSA }}


apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.allowExternalDNS.serviceAccount.annotations }}
    {{ $key }} : {{ $value }}
  {{- end }}
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns-{{.Release.Name}}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer-{{.Release.Name}}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-{{.Release.Name}}
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:

      securityContext:
        fsGroup: 65534

      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: bitnami/external-dns:0.7.1
        args:
        - --source=service
        - --source=ingress
        - --domain-filter={{ .Values.allow_external_dns.domainFilter }} # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --provider=aws
        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
        - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
        - --registry=txt
        - --interval=30s
        - --txt-owner-id= {{ .Values.allow_external_dns.txtOwnerID }}
{{ end }}